### PR TITLE
fix: add support for platform testing

### LINKED ISSUE #152: test: failing CheckPlatformName test
**Description**

There is a failing test on `check_platform_name`, after the project is generated.

**Reproductive steps**

1. Generate Very Good Flutter Plugin (from .):
```sh
very_good create flutter_plugin my_plugin
```

2. Get `check_platform_name` dependencies (from my_plugin/my_plugin/example/actions/check_platform_name):
```sh
flutter pub get
```

3. Run tests:
```sh
flutter test
```

See that there is one test failure on with "CheckPlatformName show correct description".

**Expected behaviour**

There should be no test failures, regardless of the host platform.

**Requirements**

- [ ] All `chec_platform_name` action test should pass.

### PR DESCRIPTION
**Pull request by wolfenrain**
## Status

**READY**

## Description

Closes #152 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: src/my_plugin/my_plugin/example/actions/check_platform_name/lib/src/check_platform_name.dart [hunk 1]
```diff
@@ -14,15 +14,39 @@ import 'package:fluttium/fluttium.dart';
 /// {@endtemplate}
 class CheckPlatformName extends Action {
   /// {@macro check_platform_name}
-  const CheckPlatformName();
+  const CheckPlatformName({
+    bool Function() isAndroid = _platformIsAndroid,
```
Comment (alestiago) [inline src/my_plugin/my_plugin/example/actions/check_platform_name/lib/src/check_platform_name.dart:18]: Should all these be marked as visibleForTesting?

**Review by alestiago — APPROVED** [review]
